filter:
    paths:
        - src/

before_commands:
    - 'composer self-update'
    - 'composer install --no-interaction --prefer-source --dev'

tools:
    sensiolabs_security_checker: true
    php_code_coverage: true
